server:
  port: 8005
spring:
  application:
    name: ${web.application.name}
  freemarker:
    request-context-attribute: request
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    settings:
      number_format: 0.##
eureka:
  client:
    service-url:
      defaultZone: http://192.168.55.39:8001/eureka
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
logging: 
  config: classpath:log4j2.xml
web:
  application:
    name: yto-web-bm-test
service:
  application:
    name: yto-bm-service-test
